version: '2'
services:
  web:
    image: moiwa/mws:latest
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: sample_db
    image: postgres:9.5
    volumes:
      - sample_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tonyann
      - POSTGRES_USER=singh
      - POSTGRES_DB=mwsdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  sample_db: {}